class LyricsMP3Player{
  constructor(e) {if(e)for(var t in e)void 0 !== this[t] && e.hasOwnProperty(t) && (this[t] = e[t]);}    
  id = "lyricDisplay"
  currentStyle = "currentLne"
  prefixLinId = "lyrics-line"
  showLines = 4
  clickable = !0
  clickEventName = "LyricToClick"
  setLrc(e) {this.tags = {};this.lrc = [];this.rangeLrc = [];var t = /\[([a-z]+):(.*)\].*/,n = /(\[[0-9.:\[\]]*\])+(.*)/,i = /\[([0-9]+):([0-9.]+)\]/,a = e.split(/[\r\n]/);for(var r = 0; r < a.length; r++) {var o = t.exec(a[r]);if(o && o[0])this.tags[o[1]] = o[2];else {var l = n.exec(a[r]);if(l && l[0])for(var s = l[1].replace(/\]\[/g, "],[").split(","), u = 0; u < s.length; u++) {var c = i.exec(s[u]);c && c[0] && this.lrc.push({starttime: 60 * parseInt(c[1], 10) + parseFloat(c[2]),line: l[2]})}}};this.lrc.sort(function(e, t) {return e.starttime - t.starttime});for(r = 0; r < this.showLines; r++) this.rangeLrc.push({starttime: -1,endtime: 0,line: "&nbsp;"});var d = 0,m = "";for(r = 0; r < this.lrc.length; r++) {var endtime = parseFloat(this.lrc[r].starttime);this.rangeLrc.push({starttime: d,endtime: endtime,line: m}),d = endtime,m = this.lrc[r].line;};this.rangeLrc.push({starttime: d,endtime: 999.99,line: m});for(r = 0; r < this.showLines; r++)this.rangeLrc.push({starttime: -1,endtime: 0,line: "&nbsp;"});this.totalLines = this.rangeLrc.length,this.currentLine = 0;var p = document.getElementById(this.id);p.innerHTML = "";var f = document.createElement("ul");p.appendChild(f);for(r = 0; r < this.totalLines; r++) {var g = document.createElement("li");g.innerHTML = this.rangeLrc[r].line,g.innerHTML || (g.innerHTML = "&nbsp;"),g.setAttribute("id", this.prefixLinId + r),this.clickable && (g.onclick = this.lineToClick(this, r), g.style.cursor = "pointer"),f.appendChild(g)}for(r = this.showLines; r < this.totalLines; r++)document.getElementById(this.prefixLinId + r).style.display = "none";this.move(0)}
  lineToClick(n, i) {return function() {var e = {time: n.rangeLrc[i].starttime},t = new CustomEvent(n.clickEventName,{detail: e,bubbles: !0});document.getElementById(n.prefixLinId + i).dispatchEvent(t)}}
  move(e){for(var t = 0; t < this.totalLines; t++)if(e >= this.rangeLrc[t].starttime && e < this.rangeLrc[t].endtime) {this.currentLine = t;var n = this.currentLine - this.showLines,i = this.currentLine + this.showLines;for(t = 0; t < this.totalLines; t++) {var a = document.getElementById(this.prefixLinId + t);a.style.display = n <= t && t <= i ? "block" : "none",t == this.currentLine ? a.className = this.currentStyle : a.className = ""}return}}
};window.LyricsMP3Player = LyricsMP3Player