var listMp3 = {
  "ABThree - Nyanyian Cintamu":"https://dirkncl.github.io/RadioAndMusicPlayer/media/ABThree - Nyanyian Cintamu.mp3",
  "Rama Aiphama - Dinda Bestari":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Rama Aiphama - Dinda Bestari.mp3",
  "John Denver - Leaving On A Jet Plane":"https://dirkncl.github.io/RadioAndMusicPlayer/media/John Denver - Leaving On A Jet Plane.mp3",        
  "Black Sabbath - Changes":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Black Sabbath - Changes.mp3",
  "Broery Pesulima - Senja Kelabu":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Broery Pesulima - Senja Kelabu.mp3",
  "Celline Dion - The Power of Love":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Celline Dion - The Power of Love.mp3",
  "Firehouse - Love of A Lifetime":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Firehouse - Love of a Lifetime.mp3",
  "Franky & Jane - Di Ladang Bunga, Franky S":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Franky & Jane - Di Ladang Bunga, Franky S.mp3",
  "Tipe X - Kamu nggak Sendirian":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Tipe X - Kamu nggak Sendirian.mp3",
  "Jimmy Harven - Where Are You Now":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Jimmy Harven - Where Are You Now.mp3",
  "Kenny Rogers - Evening Star":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Kenny Rogers - Evening Star.mp3",
  "Kenny Rogers - The Gambler":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Kenny Rogers - The Gambler.mp3",
  "Trisha Yearwood - For Reason I've Forgotten":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Trisha Yearwood - For Reason I've Forgotten.mp3",
  "Victor Hutabarat - Terkenang Selalu":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Victor Hutabarat - Terkenang Selalu.mp3",
  "White Lion - You're All I Need":"https://dirkncl.github.io/RadioAndMusicPlayer/media/White Lion - You're All I Need.mp3",
  "Kenny Rogers And Dolly Parton - Islands In The Stream":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Kenny Rogers and Dolly Parton - Islands In The Stream.mp3",
  "Linda Ronstad and Aaron Nevile - Don't Know Much":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Linda Ronstad and Aaron Nevile - Don't Know Much.mp3",
  "Pussycat - Mississipi":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Pussycat - Mississipi.mp3",
  "Gina T - Sail Over Seven Seas":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Gina T - Sail Over The Sea.mp3",
  "ABBA - Super Trouper":"https://dirkncl.github.io/RadioAndMusicPlayer/media/ABBA - Super Trouper.mp3",
  "Alan Jackson - Here In The Real World":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Alan Jackson - Here In The Real World.mp3",
  "Beegees - Don't Forget to Remember":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Beegees - Don't Forget to Remember.mp3",
  "Boney M - Consuela Biaz (1981)":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Boney M - Consuela Biaz (1981).mp3",
  "Boney M - El Lute (20.08.1979)":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Boney M - El Lute (20.08.1979).mp3",
  "Boney M - I'm Born Again":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Boney M - I'm Born Again.mp3",
  "Boney M - Somewhere In The World":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Boney M - Somewhere in the World.mp3",
  "Boney M - Going Back West":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Boney M - Going Back West.mp3",
  "Boyzone - Nobody Knows":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Boyzone - Nobody Knows.mp3",
  "Bunga Citra Lestari - Karena Ku Cinta Kau":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Bunga Citra Lestari - Karena Ku Cinta Kau.mp3",
  "De Four Tak - Sonja 1970":"https://dirkncl.github.io/RadioAndMusicPlayer/media/De Four Tak - Sonja 1970.mp3",
  "Ebiet G.Ade - Berita Kepada Kawan":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Ebiet G.Ade - Berita kepada kawan.mp3",
  "Firehouse - Here For You":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Firehouse - Here For You.mp3",
  "Michael Learn To Rock - That's Why":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Michael Learn To Rock - That's Why(You Go Away)(Jascha Richter).mp3",
  "Nazareth - Dream On":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Nazareth - Dream On.mp3",
  "Peter Maffay - Du 1970":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Peter Maffay - Du 1970.mp3",
  "Pussycat - Smile":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Pussycat - Smile.mp3",
  "Mandisa - Dear John":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Mandisa - Dear John.mp3",
  "Mandisa - Overcomer":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Mandisa - Overcomer.mp3",
  "Rosy and Andres - My Love":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Rosy and Andres - My Love.mp3",
  "Shania Twain - You're Still The One":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Shania Twain - You're Still The One.mp3",
  "Theo Vaness - I Go My Own Way":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Theo Vaness - I Go My Own Way.mp3",
  "Tumbleweeds - Somewhere Between":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Tumbleweeds - Somewhere Between.mp3",
  "Vengaboys - Your Place Or Mine":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Vengaboys - Your Place Or Mine.mp3",
  "Tantowi Yahya & Pinky Warow - You're My Kind Of Woman, My Kind Of Man (Vince Gill)":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Tantowi Yahya/Tantowi Yahya & Pinky Warow - You're My Kind of Woman, My Kind of Man (Vince Gill).mp3",
  "Tantowi Yahya - Balada Pelaut":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Tantowi Yahya/Tantowi Yahya - Balada Pelaut.mp3",
  "Tantowi Yahya - Biar Jo":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Tantowi Yahya/Tantowi Yahya - Biar Jo.mp3",
  "Tantowi Yahya - Hidupku Sunyi, Charles Hutagalung":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Tantowi Yahya/Tantowi Yahya - Hidupku Sunyi, Charles Hutagalung.mp3",
  "Tantowi Yahya - Kalo Mo Pikir":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Tantowi Yahya/Tantowi Yahya - Kalo Mo Pikir.mp3",
  "Tantowi Yahya - Malam Minggu":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Tantowi Yahya/Tantowi Yahya - Malam Minggu.mp3",
  "Tantowi Yahya - Mo Bilang Apa":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Tantowi Yahya/Tantowi Yahya - Mo Bilang Apa.mp3",
  "Tantowi Yahya - Nusantara, Tony Koeswoyo":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Tantowi Yahya/Tantowi Yahya - Nusantara, Tony Koeswoyo.mp3",
  "Tantowi Yahya - Nyanda Mo Balaeng":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Tantowi Yahya/Tantowi Yahya - Nyanda Mo Balaeng.mp3",
  "Tantowi Yahya - Old Country, Bobby Garden":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Tantowi Yahya/Tantowi Yahya - Old Country, Bobby Garden.mp3",
  "Tantowi Yahya - Pigi Jo Deng Dia":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Tantowi Yahya/Tantowi Yahya - Pigi Jo Deng Dia.mp3",
  "Tantowi Yahya - Polo Pa Kita":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Tantowi Yahya/Tantowi Yahya - Polo Pa Kita.mp3",
  "Tantowi Yahya - Pulang Jo":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Tantowi Yahya/Tantowi Yahya - Pulang Jo.mp3",
  "Tantowi Yahya - So Nyanda Guna":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Tantowi Yahya/Tantowi Yahya - So Nyanda Guna.mp3",
  "Tantowi Yahya - The Heart That You Own, Dwighyt Yoakam":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Tantowi Yahya/Tantowi Yahya - The Heart that You Own, Dwighyt Yoakam.mp3",
  "Tantowi Yahya Dan Mark Alan - Love Is Desire, Mark Alan Thread Gill":"https://dirkncl.github.io/RadioAndMusicPlayer/media/Tantowi Yahya/Tantowi Yahya dan Mark Alan - Love is desire, Mark Alan Thread Gill.mp3"
}
