var rawList = [
  "Avenged Sevenfold - Dear God(orig)",
  "Avenged Sevenfold - Dear God",
  "Vince Gill - Go Rest High On That Mountain",
  "Frida Wallin - When I Am Calling Your Name",
  "ABThree - Nyanyian Cintamu",
  "Rama Aiphama - Dinda Bestari",
  "John Denver - Leaving On A Jet Plane",        
  "Black Sabbath - Changes",
  "Broery Pesulima - Senja Kelabu",
  "Celline Dion - The Power of Love",
  "Firehouse - Love of A Lifetime",
  "Franky & Jane - Di Ladang Bunga, Franky S",
  "Tipe X - Kamu nggak Sendirian",
  "Jimmy Harven - Where Are You Now",
  "Kenny Rogers - Evening Star",
  "Kenny Rogers - The Gambler",
  "Trisha Yearwood - For Reason I've Forgotten",
  "Victor Hutabarat - Terkenang Selalu",
  "White Lion - You're All I Need",
  "Kenny Rogers and Dolly Parton - Islands In The Stream",
  "Linda Ronstad and Aaron Nevile - Don't Know Much",
  "Pussycat - Mississipi",
  "Gina T - Sail Over The Sea",
  "ABBA - Super Trouper",
  "Alan Jackson - Here In The Real World",
  "Beegees - Don't Forget to Remember",
  "Boney M - Consuela Biaz (1981)",
  "Boney M - El Lute (20.08.1979)",
  "Boney M - I'm Born Again",
  "Boney M - Somewhere in the World",
  "Boney M - Going Back West",
  "Boyzone - Nobody Knows",
  "Bunga Citra Lestari - Karena Ku Cinta Kau",
  "De Four Tak - Sonja 1970",
  "Ebiet G.Ade - Berita kepada kawan",
  "Firehouse - Here For You",
  "Michael Learn To Rock - That's Why(You Go Away)(Jascha Richter)",
  "Nazareth - Dream On",
  "Peter Maffay - Du 1970",
  "Pussycat - Smile",
  "Mandisa - Dear John",
  "Mandisa - Overcomer",
  "Rosy and Andres - My Love",
  "Shania Twain - You're Still The One",
  "Theo Vaness - I Go My Own Way",
  "Tumbleweeds - Somewhere Between",
  "Vengaboys - Your Place Or Mine",
  "Tantowi Yahya/Tantowi Yahya & Pinky Warow - You're My Kind of Woman, My Kind of Man (Vince Gill)",
  "Tantowi Yahya/Tantowi Yahya - Balada Pelaut",
  "Tantowi Yahya/Tantowi Yahya - Biar Jo",
  "Tantowi Yahya/Tantowi Yahya - Hidupku Sunyi, Charles Hutagalung",
  "Tantowi Yahya/Tantowi Yahya - Kalo Mo Pikir",
  "Tantowi Yahya/Tantowi Yahya - Malam Minggu",
  "Tantowi Yahya/Tantowi Yahya - Mo Bilang Apa",
  "Tantowi Yahya/Tantowi Yahya - Nusantara, Tony Koeswoyo",
  "Tantowi Yahya/Tantowi Yahya - Nyanda Mo Balaeng",
  "Tantowi Yahya/Tantowi Yahya - Old Country, Bobby Garden",
  "Tantowi Yahya/Tantowi Yahya - Pigi Jo Deng Dia",
  "Tantowi Yahya/Tantowi Yahya - Polo Pa Kita",
  "Tantowi Yahya/Tantowi Yahya - Pulang Jo",
  "Tantowi Yahya/Tantowi Yahya - So Nyanda Guna",
  "Tantowi Yahya/Tantowi Yahya - The Heart that You Own, Dwighyt Yoakam",
  "Tantowi Yahya/Tantowi Yahya dan Mark Alan - Love is desire, Mark Alan Thread Gill"
];window.listMp3 = {};for(var i = 0;i<rawList.length;i++){listMp3[rawList[i]] = ''}

